### ISSUE TITLE
User Story 1: Display the Result to User

### ISSUE THREAD

**Issue by Mah-N** [Grace-YuGuo/rock-paper-scissors-lizard-spock-game#4]
**Must do**- 
**As a** user, **I want to** see the result of the game after each round,
**So that I can** know if I won, lost, or drew against the computer.

## Acceptance Criteria:
* The outcome win, lose, or draw is displayed to the user after each round.
* The result is shown in a clear and easily understandable manner.
* As a game designer, I want the user to see what the computer has selected so that the result can be displayed according to the game rules.

## Tasks:
- [ ] Implement logic to determine the outcome of the game.
- [ ] Create a user interface element to display the result.
- [ ] Make sure the result is updated and displayed after each round.
