### ISSUE TITLE
User Story 2: Select Option

### ISSUE THREAD

**Issue by Mah-N** [Grace-YuGuo/rock-paper-scissors-lizard-spock-game#5]
**Must do**-
**As a** user, **I want to** select one of the five options (Rock, Paper, Scissors, Lizard, or Spock),
**So that I can** make my move in the game.

## Acceptance Criteria:
* The user can select one of the five options: Rock, Paper, Scissors, Lizard, or Spock.
* The selected option is highlighted or indicated on the user interface.

## Tasks:
- [ ] Develop a user interface for selecting the options.
- [ ] Implement functionality to capture and process the user's selection.
- [ ] Make sure the selected option is visually indicated on the screen.
