### ISSUE TITLE
User Story 3: Understand the Rules

### ISSUE THREAD

**Issue by Mah-N** [Grace-YuGuo/rock-paper-scissors-lizard-spock-game#6]
**Must do-**
**As a** user, **I want to** see clear instructions on how to play the game,
**So that I can** understand the rules and play the game correctly.

## Acceptance Criteria:
* The game rules are clearly explained on the interface.
* Instructions are easily accessible from the main game screen.
* The rules include a description of how each option interacts with the others.
* The winner is determined based on the rules of the game.

## Tasks:
- [ ] Write a clear and concise explanation of the game rules.
- [ ] Add the image also to explain the game rules.
- [ ] Design a user interface element to display the rules.
- [ ] Make sure the rules are accessible from the main game screen.
